[build]
  command = "CI= npm run netlify:build"
  functions = "lambda"
  publish = "__sapper__/export"

[dev]
  framework = "sapper"

[[redirects]]
  from = "/teste/*"
  to = "/.netlify/functions/prov-teste?id=:splat"
  status = 302